In [1]:
import numpy as np
from sklearn.gaussian_process import GaussianProcess
from matplotlib import pyplot as pl

np.random.seed(1)
def f(x):
    return x * np.sin(x)


In [14]:
X = np.atleast_2d([1., 3., 5., 6., 7., 8.]).T
X

array([[ 1.],
       [ 3.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.]])

In [7]:
y = f(X).ravel()
y

array([ 0.84147098,  0.42336002, -4.79462137, -1.67649299,  4.59890619,
        7.91486597])

In [15]:
x = np.atleast_2d(np.linspace(0, 10, 1000)).T
x

array([[  0.        ],
       [  0.01001001],
       [  0.02002002],
       [  0.03003003],
       [  0.04004004],
       [  0.05005005],
       [  0.06006006],
       [  0.07007007],
       [  0.08008008],
       [  0.09009009],
       [  0.1001001 ],
       [  0.11011011],
       [  0.12012012],
       [  0.13013013],
       [  0.14014014],
       [  0.15015015],
       [  0.16016016],
       [  0.17017017],
       [  0.18018018],
       [  0.19019019],
       [  0.2002002 ],
       [  0.21021021],
       [  0.22022022],
       [  0.23023023],
       [  0.24024024],
       [  0.25025025],
       [  0.26026026],
       [  0.27027027],
       [  0.28028028],
       [  0.29029029],
       [  0.3003003 ],
       [  0.31031031],
       [  0.32032032],
       [  0.33033033],
       [  0.34034034],
       [  0.35035035],
       [  0.36036036],
       [  0.37037037],
       [  0.38038038],
       [  0.39039039],
       [  0.4004004 ],
       [  0.41041041],
       [  0.42042042],
       [  0